version: '3.4'

services:
  client:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: src
      dockerfile: Client/Dockerfile
  server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: src
      dockerfile: Server/Dockerfile
    